name: better-npm-audit

on:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  npm-audit:
    uses: js-soft/github-actions/.github/workflows/handle-npm-audit.yml@main
    secrets:
      github-token: ${{ secrets.GH_PAT }}
